### ISSUE TITLE
Something wrong about the semantic_mask and the instance_mask

### ISSUE THREAD

**Issue by luooofan** [RocketFlash/CAP_augmentation#1]
Thanks for your great work.

But I encountered some problems when I run the code.
To be specific, there seems to be something wrong about the semantic_mask and the instance_mask.
The code can't draw instance(or semantic) segmentation image correctly.

https://github.com/RocketFlash/CAP_augmentation/blob/5db059901bcf6bf05f140f9ccec5e500b7551164/src/cap_aug.py#L281-L301

I can't understand the logic stream in these codes above.

I try to modify them to the following:
```python
image_dst, coords, mask = self.paste_object(image_dst, image_src, x_coord, y_coord, self.random_h_flip, self.random_v_flip)
if coords:
    coords_all.append(coords)
    x1, y1, x2, y2 = coords
    semantic_mask[y1:y2, x1:x2] = mask
    instance_mask[y1:y2, x1:x2] = mask*(idx+1)
```

And it's actually works.

So, I want to know more about the code snippet above. Can it work rensonably？

**Comment by RocketFlash** [comment]
Hi, @Luoofan !

The idea of this part of code is to cover the situation when masks are near and intersect (see an example below). If you will use your version of this part of code current object mask will completely replace all pixel values in the  [y1:y2, x1:x2] region. What kind of problems do you have with masks ? What values they have ?

<img width="316" alt="Screenshot 2021-04-18 at 23 31 28" src="https://user-images.githubusercontent.com/7099937/115160123-3b4bce00-a09f-11eb-9604-a75768b5689b.png">

**Comment by luooofan** [comment]
Hi, @RocketFlash !
Thanks for your reply, now I konw your idea of this part of code. It's ok. I don't take the loop into account before.

But I think the line 
https://github.com/RocketFlash/CAP_augmentation/blob/5db059901bcf6bf05f140f9ccec5e500b7551164/src/cap_aug.py#L287
should be modified to below:
```python
curr_mask_ins = curr_mask*(idx+1)
```
Otherwise the first pasted object will be considered as the background (values equal 0).

What do you think about this?

**Comment by RocketFlash** [comment]
@Luoofan you're right! Thank you! 👍  Fixed it in the last commit
