### ISSUE TITLE
How to integrate this with detectron2

### ISSUE THREAD

**Issue by hungryGeek16** [RocketFlash/CAP_augmentation#6]
Hi, @RocketFlash ,

* Thanks for making this up, can u please tell me how to integrate cut-paste with detectron2 augmentations.

**Comment by engrjav** [comment]
@hungryGeek16  @RocketFlash  i have a json file with masks generated from detectron2 in rle format, please guide me how to convert json annotations (with compressed RLE mask) to csv for your code. so far since a week i am stuck on this issue and nothing seems to work
